version: '3.4'
  
services:
  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      image: ${elasticsearch.image.name}
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - elk
    deploy:
      mode: ${elasticsearch.deploy.mode}
      replicas: ${elasticsearch.deploy.replicas}
      endpoint_mode: ${elasticsearch.deploy.endpoint_mode}
  kibana:
    image: ${kibana.image.name}
    ports:
      - ${kibana.port}:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3
    logstash:
    hostname: logstash
    command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elasticsearch\
" ] } }'"
    image: ${logstash.image.name}
    ports:
        - "10514:10514/tcp"
        - "10514:10514/udp"
        - "12201:12201/udp"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
networks:
  elk:
    driver: overlay
