debug: "true"
elastisearch:
  image:
    version: 5
  deploy:
    endpoint_mode: dnsrr
    mode: replicated
    replicas: 2
logstash:
  image:
    version: alpine
  deploy:
    mode: replicated
    replicas: 1
    endpoint_mode: dnsrr
kibana:
  image:
    version: latest
  deploy:
    mode: replicated
    replicas: 1
    endpoint_mode: dnsrr
  port: 5601
