debug: "true"
elastisearch:
  image:
    name: elasticsearch
    tag: 5
  deploy:
    endpoint_mode: dnsrr
    mode: replicated
    replicas: 2
logstash:
  image:
    name: logstash
    tag: alpine
  deploy:
    mode: replicated
    replicas: 1
    endpoint_mode: dnsrr
kibana:
  image:
    name: kibana
    tag: latest
  deploy:
    mode: replicated
    replicas: 1
    endpoint_mode: dnsrr
  port: 5601
