elasticsearch:
  image:
    name: elasticsearch:5
  deploy:
    mode: replicated
    replicas: 2
    
kibana:
  image:
    name: kibana:latest
  port: 5601
  deploy:
    mode: replicated
    replicas: 2
    
logstash:
  image:
    name: logstash:alpine
  deploy:
    mode: replicated
    replicas: 2
    
